"""Freddie Mac SFLLD file layout: column contract for origination and performance files.

Source: file_layout_july_2026.xlsx (Single-Family Loan-Level Dataset, Release 47, July 2026).
Files are pipe-delimited with no header row; column order below must match the xlsx exactly.
"""

ORIG_FIELDS = [
    "classic_fico",
    "first_payment_date",
    "first_time_homebuyer_flag",
    "maturity_date",
    "msa",
    "mi_pct",
    "num_units",
    "occupancy_status",
    "cltv",
    "dti",
    "orig_upb",
    "ltv",
    "orig_interest_rate",
    "channel",
    "ppm_flag",
    "amortization_type",
    "property_state",
    "property_type",
    "postal_code",
    "loan_seq_no",
    "loan_purpose",
    "orig_loan_term",
    "num_borrowers",
    "seller_name",
    "super_conforming_flag",
    "pre_harp_loan_seq_no",
    "special_eligibility_program",
    "harp_indicator",
    "property_valuation_method",
    "io_indicator",
    "vantagescore4",
]

PERF_FIELDS = [
    "loan_seq_no",
    "reporting_period",
    "current_upb",
    "dlq_status",
    "loan_age",
    "remaining_months_to_maturity",
    "defect_settlement_date",
    "modification_flag",
    "zero_balance_code",
    "zero_balance_effective_date",
    "current_interest_rate",
    "current_non_interest_bearing_upb",
    "ddlpi",
    "mi_recoveries",
    "net_sale_proceeds",
    "non_mi_recoveries",
    "total_expenses",
    "legal_costs",
    "maintenance_costs",
    "taxes_and_insurance",
    "misc_expenses",
    "actual_loss",
    "cumulative_modification_cost",
    "interest_rate_step_indicator",
    "payment_deferral_flag",
    "estimated_ltv",
    "zero_balance_removal_upb",
    "delinquent_accrued_interest",
    "delinquency_due_to_disaster",
    "borrower_assistance_plan",
    "current_month_modification_cost",
    "interest_bearing_upb",
    "mi_cancellation_indicator",
    "servicer_name",
    "bankruptcy_cramdown_costs",
]

ORIG_PK = "loan_seq_no"
PERF_PK = ("loan_seq_no", "reporting_period")
